import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const cfg=window.KPA_SUPABASE_CONFIG||{};
const configured=cfg.url&&cfg.anonKey&&!cfg.url.includes("YOUR_PROJECT")&&!cfg.anonKey.includes("YOUR_SUPABASE");
const sb=configured?createClient(cfg.url,cfg.anonKey):null;
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const esc=(v="")=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const fmt=v=>v?new Date(v).toLocaleString(undefined,{year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const localInput=v=>v?new Date(v).toISOString().slice(0,16):"";
const badge=v=>`<span class="badge ${esc(v||"")}">${esc(String(v||"—").replaceAll("_"," "))}</span>`;
const roles={super_admin:"Super Admin",school_admin:"School Admin",editor:"Content Editor",admissions:"Admissions Officer",viewer:"Viewer"};
let sessionUser=null,profile=null,admissions=[],news=[],announcements=[],enquiries=[],adminUsers=[];

function can(...allowed){return !!profile&&allowed.includes(profile.role)}
function audit(action,entityType,entityId,details={}){if(!sb||!profile)return;return sb.from("audit_log").insert({actor_user_id:sessionUser.id,actor_role:profile.role,action,entity_type:entityType,entity_id:String(entityId||""),details}).then(()=>{}).catch(()=>{})}
function slugify(v){return String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function openModal(id){$("#"+id)?.classList.add("open")}
function closeModal(id){$("#"+id)?.classList.remove("open")}

async function getProfile(user){const {data,error}=await sb.from("admin_users").select("*").eq("user_id",user.id).eq("is_active",true).single();if(error)return null;return data}

async function signIn(email,password){return sb.auth.signInWithPassword({email,password})}

async function boot(){
  if(!sb){$("#loginMsg").textContent="Supabase is not configured.";return}
  const {data:{session}}=await sb.auth.getSession();
  if(!session)return;
  const p=await getProfile(session.user);
  if(!p){await sb.auth.signOut();$("#loginMsg").textContent="This account is not authorized for the KPA dashboard.";return}
  sessionUser=session.user;profile=p;
  $("#loginScreen").classList.add("hidden");$("#dashboard").classList.remove("hidden");
  $("#userName").textContent=profile.display_name||"Administrator";$("#userEmail").textContent=sessionUser.email||"";$("#roleLabel").textContent=roles[profile.role]||profile.role;
  $$('[data-roles]').forEach(el=>{const allowed=el.dataset.roles.split(',');el.classList.toggle('hidden',!allowed.includes(profile.role))});
  if(!can("super_admin"))$("#newUser")?.classList.add("hidden");
  await refreshAll();
  if(sessionUser.user_metadata?.must_reset_password){$('#passwordNotice').textContent='This account was created with a temporary password. Change it now before continuing.';openModal('passwordModal')}
}

$("#loginForm")?.addEventListener("submit",async e=>{e.preventDefault();if(!sb){$("#loginMsg").textContent="Supabase is not configured.";return}$("#loginMsg").textContent="Signing in…";const {data,error}=await signIn($("#email").value,$("#password").value);if(error){$("#loginMsg").textContent=error.message;return}const p=await getProfile(data.user);if(!p){await sb.auth.signOut();$("#loginMsg").textContent="This account is not authorized.";return}location.reload()});
$("#signOut")?.addEventListener("click",async()=>{await sb?.auth.signOut();location.reload()});

$$('[data-panel]').forEach(btn=>btn.addEventListener('click',()=>showPanel(btn.dataset.panel)));
$$('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>showPanel(btn.dataset.jump)));
function showPanel(id){$$('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===id));$("#pageTitle").textContent=$(`[data-panel="${id}"]`)?.textContent||id}
$$('[data-close]').forEach(btn=>btn.addEventListener('click',()=>closeModal(btn.dataset.close)));
$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.open').forEach(m=>m.classList.remove('open'))});

async function refreshAll(){const jobs=[loadStats()];if(can('super_admin','school_admin','admissions','viewer'))jobs.push(loadAdmissions(),loadEnquiries());if(can('super_admin','school_admin','editor','viewer'))jobs.push(loadNews(),loadAnnouncements());if(can('super_admin','school_admin'))jobs.push(loadSettings(),loadUsers());await Promise.all(jobs)}

async function loadStats(){
  const queries=[];
  const qAdm=can('super_admin','school_admin','admissions','viewer');const qContent=can('super_admin','school_admin','editor','viewer');
  queries.push(qAdm?sb.from('admission_applications').select('*',{count:'exact',head:true}).eq('status','new'):Promise.resolve({count:0}));
  queries.push(qAdm?sb.from('admission_applications').select('*',{count:'exact',head:true}).eq('status','review'):Promise.resolve({count:0}));
  queries.push(qContent?sb.from('news_articles').select('*',{count:'exact',head:true}).eq('status','published').is('deleted_at',null):Promise.resolve({count:0}));
  queries.push(qContent?sb.from('announcements').select('*',{count:'exact',head:true}).eq('is_active',true).is('deleted_at',null):Promise.resolve({count:0}));
  const [a,b,c,d]=await Promise.all(queries);$("#sNew").textContent=a.count||0;$("#sReview").textContent=b.count||0;$("#sNews").textContent=c.count||0;$("#sAnn").textContent=d.count||0;
}

// ADMISSIONS
async function loadAdmissions(){const {data,error}=await sb.from('admission_applications').select('*').order('created_at',{ascending:false});if(error){console.error(error);return}admissions=data||[];renderAdmissions();renderRecent();const sent=admissions.some(x=>x.email_status==='sent');$("#emailSystemStatus").textContent=sent?'Delivery confirmed':'Awaiting configured/test delivery'}
function filteredAdmissions(){const q=($("#admissionSearch")?.value||'').toLowerCase().trim(),status=$("#admissionFilter")?.value||'all',sort=$("#admissionSort")?.value||'newest';let rows=admissions.filter(x=>status==='all'||x.status===status).filter(x=>!q||[x.reference_number,x.student_first_name,x.student_last_name,x.parent_name,x.parent_phone,x.parent_email,x.applying_for_class].join(' ').toLowerCase().includes(q));rows.sort((a,b)=>sort==='oldest'?new Date(a.created_at)-new Date(b.created_at):new Date(b.created_at)-new Date(a.created_at));return rows}
function renderAdmissions(){const rows=filteredAdmissions();$("#admissionRows").innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${esc(x.reference_number)}</strong></td><td>${esc(x.student_first_name+' '+x.student_last_name)}</td><td>${esc(x.applying_for_class)}</td><td>${esc(x.parent_name)}<br><small>${esc(x.parent_phone)}</small></td><td>${badge(x.status)}</td><td>${badge(x.email_status||'pending')}</td><td>${fmt(x.created_at)}</td><td><button class="mini-btn" data-view-admission="${x.id}">View</button></td></tr>`).join(''):`<tr><td colspan="8" class="empty">No applications found.</td></tr>`;$$('[data-view-admission]').forEach(b=>b.onclick=()=>viewAdmission(b.dataset.viewAdmission))}
function renderRecent(){const rows=admissions.slice(0,5);$("#recentAdmissions").innerHTML=rows.length?rows.map(x=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><strong>${esc(x.student_first_name+' '+x.student_last_name)}</strong><br><small>${esc(x.reference_number)} • ${esc(x.applying_for_class)} • ${esc(x.status)}</small></div>`).join(''):`<div class="empty">No applications yet.</div>`}
$("#admissionSearch")?.addEventListener('input',renderAdmissions);$("#admissionFilter")?.addEventListener('change',renderAdmissions);$("#admissionSort")?.addEventListener('change',renderAdmissions);
function viewAdmission(id){const x=admissions.find(a=>a.id===id);if(!x)return;$("#admissionModalTitle").textContent=x.reference_number;$("#admissionDetail").innerHTML=`<div class="detail-grid"><div class="detail-card"><h3>Student</h3><p><strong>${esc(x.student_first_name+' '+x.student_last_name)}</strong></p><p>DOB: ${esc(x.date_of_birth||'—')}</p><p>Gender: ${esc(x.gender||'—')}</p><p>Current school: ${esc(x.current_school||'—')}</p><p>Current class: ${esc(x.current_class||'—')}</p><p>Applying for: ${esc(x.applying_for_class)}</p><p>Session: ${esc(x.academic_session)}</p></div><div class="detail-card"><h3>Parent / Guardian</h3><p><strong>${esc(x.parent_name)}</strong></p><p>${esc(x.relationship_to_student||'')}</p><p>Phone: ${esc(x.parent_phone)}</p><p>WhatsApp: ${esc(x.parent_whatsapp||'—')}</p><p>Email: ${esc(x.parent_email)}</p><p>Address: ${esc(x.residential_address)}</p></div></div><div class="detail-card" style="margin-top:12px"><h3>Additional Information</h3><p><strong>Previous school / academic:</strong><br>${esc(x.previous_school_notes||'—')}</p><p><strong>Support information:</strong><br>${esc(x.support_information||'—')}</p><p><strong>Parent message:</strong><br>${esc(x.parent_message||'—')}</p><p><strong>Email notification:</strong> ${badge(x.email_status||'pending')} ${x.email_sent_at?`on ${fmt(x.email_sent_at)}`:''}</p>${x.email_error?`<p><strong>Email error:</strong> ${esc(x.email_error)}</p>`:''}</div>${can('super_admin','school_admin','admissions')?`<div class="detail-card" style="margin-top:12px"><label>Status<select id="admStatus">${['new','review','contacted','assessment','offered','accepted','declined','closed'].map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select></label><label>Internal Note<textarea id="admNote">${esc(x.internal_note||'')}</textarea></label><div class="form-actions"><button class="btn primary" id="saveAdmission">Save Changes</button></div></div>`:''}`;openModal('admissionModal');$("#saveAdmission")?.addEventListener('click',async()=>{const next=$("#admStatus").value,note=$("#admNote").value;if(!confirm(`Change this application status to “${next.replaceAll('_',' ')}”?`))return;const {error}=await sb.from('admission_applications').update({status:next,internal_note:note,reviewed_by:sessionUser.id,status_changed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return}await audit('update_admission','admission_application',id,{from:x.status,to:next});closeModal('admissionModal');await loadAdmissions();await loadStats()})}
$("#exportAdmissions")?.addEventListener('click',()=>{const rows=filteredAdmissions(),cols=['reference_number','student_first_name','student_last_name','applying_for_class','parent_name','parent_phone','parent_email','status','created_at'];const csv=[cols.join(','),...rows.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`kpa-admissions-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)});

// NEWS
async function loadNews(){const {data,error}=await sb.from('news_articles').select('*').is('deleted_at',null).order('created_at',{ascending:false});if(error)return;news=data||[];renderNews()}
function renderNews(){const q=($("#newsSearch")?.value||'').toLowerCase(),st=$("#newsStatus")?.value||'all';const rows=news.filter(x=>(st==='all'||x.status===st)&&(!q||[x.title,x.category,x.excerpt].join(' ').toLowerCase().includes(q)));$("#newsRows").innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${esc(x.title)}</strong><br><small>${esc(x.excerpt||'')}</small></td><td>${esc(x.category||'School')}</td><td>${badge(x.status)}</td><td>${x.featured?'Yes':'No'}</td><td>${fmt(x.published_at)}</td><td><div class="row-actions"><button class="mini-btn" data-edit-news="${x.id}">Edit</button>${can('super_admin','school_admin')?`<button class="mini-btn" data-archive-news="${x.id}">Archive</button>`:''}</div></td></tr>`).join(''):`<tr><td colspan="6" class="empty">No news found.</td></tr>`;$$('[data-edit-news]').forEach(b=>b.onclick=()=>openNews(b.dataset.editNews));$$('[data-archive-news]').forEach(b=>b.onclick=()=>archiveNews(b.dataset.archiveNews))}
$("#newsSearch")?.addEventListener('input',renderNews);$("#newsStatus")?.addEventListener('change',renderNews);$("#newNews")?.addEventListener('click',()=>openNews());
function openNews(id=null){const f=$("#newsForm");f.reset();f.elements.id.value='';$("#deleteNews").classList.add('hidden');$("#newsImagePreview").classList.remove('show');$("#newsImagePreview").src='';if(id){const x=news.find(n=>n.id===id);if(!x)return;f.elements.id.value=x.id;f.elements.title.value=x.title;f.elements.category.value=x.category||'School';f.elements.status.value=x.status;f.elements.excerpt.value=x.excerpt||'';f.elements.content.value=x.content||'';f.elements.published_at.value=localInput(x.published_at);f.elements.featured.value=String(!!x.featured);f.elements.image_alt.value=x.image_alt||'';if(x.image_url){$("#newsImagePreview").src=x.image_url;$("#newsImagePreview").classList.add('show')}if(can('super_admin','school_admin'))$("#deleteNews").classList.remove('hidden')}openModal('newsModal')}
$("#newsForm input[name=image]")?.addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file);$("#newsImagePreview").src=url;$("#newsImagePreview").classList.add('show')});
$("#newsForm")?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),id=d.get('id'),existing=id?news.find(x=>x.id===id):null;let image_url=existing?.image_url||null;const image=d.get('image');if(image?.size){if(image.size>5*1024*1024){alert('Image must be 5 MB or smaller.');return}const ext=(image.name.split('.').pop()||'jpg').toLowerCase();const path=`news/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('website-media').upload(path,image,{upsert:false});if(error){alert(error.message);return}image_url=sb.storage.from('website-media').getPublicUrl(path).data.publicUrl}let slug=slugify(d.get('title'));if(id&&existing?.slug)slug=existing.slug;const status=d.get('status'),publishedInput=d.get('published_at');const payload={title:d.get('title'),slug,category:d.get('category')||'School',status,excerpt:d.get('excerpt'),content:d.get('content'),image_url,image_alt:d.get('image_alt')||null,featured:d.get('featured')==='true',published_at:status==='published'?(publishedInput?new Date(publishedInput).toISOString():(existing?.published_at||new Date().toISOString())):null,archived_at:status==='archived'?new Date().toISOString():null,updated_at:new Date().toISOString(),updated_by:sessionUser.id};if(!id)payload.created_by=sessionUser.id;const {error}=id?await sb.from('news_articles').update(payload).eq('id',id):await sb.from('news_articles').insert(payload);if(error){alert(error.message);return}await audit(id?'update_news':'create_news','news_article',id||slug,{title:payload.title,status});closeModal('newsModal');await loadNews();await loadStats()});
async function archiveNews(id){if(!confirm('Archive this story? It will stop appearing publicly.'))return;await sb.from('news_articles').update({status:'archived',archived_at:new Date().toISOString(),updated_by:sessionUser.id,updated_at:new Date().toISOString()}).eq('id',id);await audit('archive_news','news_article',id);await loadNews();await loadStats()}
$("#deleteNews")?.addEventListener('click',async()=>{const id=$("#newsForm").elements.id.value;if(!id||!confirm('Delete this story from the CMS? This action should only be used when necessary.'))return;const {error}=await sb.from('news_articles').update({deleted_at:new Date().toISOString(),updated_by:sessionUser.id,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return}await audit('delete_news','news_article',id);closeModal('newsModal');await loadNews();await loadStats()});

// ANNOUNCEMENTS
async function loadAnnouncements(){const {data,error}=await sb.from('announcements').select('*').is('deleted_at',null).order('priority',{ascending:false}).order('created_at',{ascending:false});if(error)return;announcements=data||[];renderAnnouncements()}
function annState(x){const now=Date.now();if(!x.is_active)return'inactive';if(x.starts_at&&new Date(x.starts_at).getTime()>now)return'scheduled';if(x.ends_at&&new Date(x.ends_at).getTime()<now)return'expired';return'active'}
function renderAnnouncements(){$("#announcementRows").innerHTML=announcements.length?announcements.map(x=>`<tr><td><strong>${esc(x.title)}</strong></td><td>${esc(x.message)}</td><td>${x.priority}</td><td>${x.starts_at?fmt(x.starts_at):'Now'} → ${x.ends_at?fmt(x.ends_at):'No expiry'}</td><td>${badge(annState(x))}</td><td><div class="row-actions"><button class="mini-btn" data-edit-ann="${x.id}">Edit</button>${can('super_admin','school_admin','editor')?`<button class="mini-btn" data-toggle-ann="${x.id}">${x.is_active?'Deactivate':'Activate'}</button>`:''}</div></td></tr>`).join(''):`<tr><td colspan="6" class="empty">No announcements yet.</td></tr>`;$$('[data-edit-ann]').forEach(b=>b.onclick=()=>openAnnouncement(b.dataset.editAnn));$$('[data-toggle-ann]').forEach(b=>b.onclick=()=>toggleAnnouncement(b.dataset.toggleAnn))}
$("#newAnnouncement")?.addEventListener('click',()=>openAnnouncement());
function openAnnouncement(id=null){const f=$("#announcementForm");f.reset();f.elements.id.value='';$("#deleteAnnouncement").classList.add('hidden');if(id){const x=announcements.find(a=>a.id===id);if(!x)return;f.elements.id.value=x.id;f.elements.title.value=x.title;f.elements.message.value=x.message;f.elements.link_url.value=x.link_url||'';f.elements.priority.value=x.priority??10;f.elements.starts_at.value=localInput(x.starts_at);f.elements.ends_at.value=localInput(x.ends_at);f.elements.is_active.value=String(!!x.is_active);if(can('super_admin','school_admin'))$("#deleteAnnouncement").classList.remove('hidden')}openModal('announcementModal')}
$("#announcementForm")?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),id=d.get('id');const payload={title:d.get('title'),message:d.get('message'),link_url:d.get('link_url')||null,priority:Number(d.get('priority')||10),starts_at:d.get('starts_at')?new Date(d.get('starts_at')).toISOString():null,ends_at:d.get('ends_at')?new Date(d.get('ends_at')).toISOString():null,is_active:d.get('is_active')==='true',updated_by:sessionUser.id,updated_at:new Date().toISOString()};if(payload.starts_at&&payload.ends_at&&new Date(payload.ends_at)<=new Date(payload.starts_at)){alert('Expiry must be after the start date.');return}if(!id)payload.created_by=sessionUser.id;const {error}=id?await sb.from('announcements').update(payload).eq('id',id):await sb.from('announcements').insert(payload);if(error){alert(error.message);return}await audit(id?'update_announcement':'create_announcement','announcement',id||payload.title,{title:payload.title});closeModal('announcementModal');await loadAnnouncements();await loadStats()});
async function toggleAnnouncement(id){const x=announcements.find(a=>a.id===id);if(!x)return;await sb.from('announcements').update({is_active:!x.is_active,updated_by:sessionUser.id,updated_at:new Date().toISOString()}).eq('id',id);await audit('toggle_announcement','announcement',id,{is_active:!x.is_active});await loadAnnouncements();await loadStats()}
$("#deleteAnnouncement")?.addEventListener('click',async()=>{const id=$("#announcementForm").elements.id.value;if(!id||!confirm('Delete this announcement?'))return;await sb.from('announcements').update({deleted_at:new Date().toISOString(),is_active:false,updated_by:sessionUser.id,updated_at:new Date().toISOString()}).eq('id',id);await audit('delete_announcement','announcement',id);closeModal('announcementModal');await loadAnnouncements();await loadStats()});

// ENQUIRIES
async function loadEnquiries(){const {data,error}=await sb.from('contact_enquiries').select('*').order('created_at',{ascending:false});if(error)return;enquiries=data||[];renderEnquiries()}
function renderEnquiries(){const q=($("#enquirySearch")?.value||'').toLowerCase(),st=$("#enquiryFilter")?.value||'all';const rows=enquiries.filter(x=>(st==='all'||x.status===st)&&(!q||[x.name,x.email,x.phone,x.enquiry_type,x.message].join(' ').toLowerCase().includes(q)));$("#enquiryRows").innerHTML=rows.length?rows.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(x.enquiry_type||'General')}</td><td>${esc(x.phone||'')}<br><small>${esc(x.email||'')}</small></td><td>${badge(x.status)}</td><td>${fmt(x.created_at)}</td><td><button class="mini-btn" data-view-enquiry="${x.id}">View</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">No enquiries found.</td></tr>`;$$('[data-view-enquiry]').forEach(b=>b.onclick=()=>viewEnquiry(b.dataset.viewEnquiry))}
$("#enquirySearch")?.addEventListener('input',renderEnquiries);$("#enquiryFilter")?.addEventListener('change',renderEnquiries);
function viewEnquiry(id){const x=enquiries.find(e=>e.id===id);if(!x)return;$("#enquiryDetail").innerHTML=`<div class="detail-card"><p><strong>${esc(x.name)}</strong></p><p>Phone: ${esc(x.phone||'—')}</p><p>Email: ${esc(x.email||'—')}</p><p>Type: ${esc(x.enquiry_type||'General')}</p><p><strong>Message</strong><br>${esc(x.message)}</p></div>${can('super_admin','school_admin','admissions')?`<label>Status<select id="enquiryStatus">${['new','in_progress','resolved','closed'].map(s=>`<option value="${s}" ${x.status===s?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select></label><label>Internal Note<textarea id="enquiryNote">${esc(x.internal_note||'')}</textarea></label><button class="btn primary" id="saveEnquiry">Save</button>`:''}`;openModal('enquiryModal');$("#saveEnquiry")?.addEventListener('click',async()=>{await sb.from('contact_enquiries').update({status:$("#enquiryStatus").value,internal_note:$("#enquiryNote").value,handled_by:sessionUser.id,updated_at:new Date().toISOString()}).eq('id',id);await audit('update_enquiry','contact_enquiry',id);closeModal('enquiryModal');await loadEnquiries()})}

// SETTINGS
async function loadSettings(){const {data}=await sb.from('website_settings').select('*');const f=$("#settingsForm");(data||[]).forEach(x=>{if(f.elements[x.key])f.elements[x.key].value=x.value||''})}
$("#settingsForm")?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),rows=[...d.entries()].map(([key,value])=>({key,value,updated_by:sessionUser.id,updated_at:new Date().toISOString()}));const {error}=await sb.from('website_settings').upsert(rows,{onConflict:'key'});if(error){alert(error.message);return}await audit('update_settings','website_settings','multiple');alert('Settings saved.')});

// PASSWORD
$('#changePassword')?.addEventListener('click',()=>{ $('#passwordForm').reset();$('#passwordResult').textContent='';openModal('passwordModal') });
$('#passwordForm')?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),pw=String(d.get('password')||''),confirmPw=String(d.get('confirm')||'');if(pw!==confirmPw){$('#passwordResult').textContent='Passwords do not match.';return}if(pw.length<10){$('#passwordResult').textContent='Use at least 10 characters.';return}const {error}=await sb.auth.updateUser({password:pw,data:{...sessionUser.user_metadata,must_reset_password:false}});if(error){$('#passwordResult').textContent=error.message;return}$('#passwordResult').textContent='Password updated successfully.';setTimeout(()=>closeModal('passwordModal'),900)});

// ADMIN USERS
async function loadUsers(){const {data,error}=await sb.from('admin_users').select('*').order('created_at',{ascending:true});if(error)return;adminUsers=data||[];$("#userRows").innerHTML=adminUsers.length?adminUsers.map(x=>`<tr><td><strong>${esc(x.display_name||'Administrator')}</strong></td><td>${esc(roles[x.role]||x.role)}</td><td>${badge(x.is_active?'active':'inactive')}</td><td>${fmt(x.created_at)}</td><td>${can('super_admin')?`<div class="row-actions"><button class="mini-btn" data-user-role="${x.user_id}">Role</button><button class="mini-btn" data-user-active="${x.user_id}">${x.is_active?'Deactivate':'Activate'}</button></div>`:''}</td></tr>`).join(''):`<tr><td colspan="5" class="empty">No administrators.</td></tr>`;$$('[data-user-role]').forEach(b=>b.onclick=()=>changeRole(b.dataset.userRole));$$('[data-user-active]').forEach(b=>b.onclick=()=>toggleUser(b.dataset.userActive))}
$("#newUser")?.addEventListener('click',()=>{if(!can('super_admin'))return;$("#userForm").reset();$("#userCreateResult").textContent='';openModal('userModal')});
async function invokeAdmin(body){const {data,error}=await sb.functions.invoke('manage-admin',{body});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'Admin action failed');return data}
$("#userForm")?.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget);try{const result=await invokeAdmin({action:'create',displayName:d.get('displayName'),email:d.get('email'),role:d.get('role')});$("#userCreateResult").innerHTML=`User created. Temporary password: <strong>${esc(result.temporaryPassword)}</strong><br>Copy it now and share it securely.`;await loadUsers()}catch(err){$("#userCreateResult").textContent=String(err)}});
async function toggleUser(id){const x=adminUsers.find(u=>u.user_id===id);if(!x||!confirm(`${x.is_active?'Deactivate':'Activate'} ${x.display_name||'this user'}?`))return;try{await invokeAdmin({action:'set_active',userId:id,isActive:!x.is_active});await loadUsers()}catch(e){alert(String(e))}}
async function changeRole(id){const x=adminUsers.find(u=>u.user_id===id);if(!x)return;const role=prompt('Enter role: super_admin, school_admin, editor, admissions, viewer',x.role);if(!role||role===x.role)return;try{await invokeAdmin({action:'set_role',userId:id,role});await loadUsers()}catch(e){alert(String(e))}}

boot();
