
import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const c=window.KPA_SUPABASE_CONFIG||{},ok=c.url&&c.anonKey&&!c.url.includes("YOUR_PROJECT")&&!c.anonKey.includes("YOUR_SUPABASE"),sb=ok?createClient(c.url,c.anonKey):null;
const $=(s,d=document)=>d.querySelector(s),$$=(s,d=document)=>[...d.querySelectorAll(s)],esc=(v="")=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
let user,news=[],anns=[],adms=[];
async function authAdmin(u){const {data}=await sb.from("admin_users").select("*").eq("user_id",u.id).eq("is_active",true).single();return data}
async function boot(){if(!sb)return;const {data:{session}}=await sb.auth.getSession();if(!session)return;const a=await authAdmin(session.user);if(!a){await sb.auth.signOut();return}user=session.user;$("#loginScreen").classList.add("hidden");$("#dashboard").classList.remove("hidden");$("#user").textContent=a.display_name||user.email;await Promise.all([stats(),loadNews(),loadAnns(),loadAdms()])}
$("#loginForm").onsubmit=async e=>{e.preventDefault();if(!sb){$("#loginMsg").textContent="Configure Supabase first.";return}const {data,error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(error){$("#loginMsg").textContent=error.message;return}if(!await authAdmin(data.user)){await sb.auth.signOut();$("#loginMsg").textContent="Not authorized.";return}boot()}
$("#signOut").onclick=async()=>{await sb.auth.signOut();location.reload()}
$$(".sidebar [data-panel]").forEach(b=>b.onclick=()=>{$$(".sidebar [data-panel]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".panel").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.panel).classList.add("active");$("#title").textContent=b.textContent})
$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.remove("open"))
async function stats(){const q=await Promise.all([sb.from("news_articles").select("*",{count:"exact",head:true}).eq("status","published"),sb.from("announcements").select("*",{count:"exact",head:true}).eq("is_active",true),sb.from("admission_applications").select("*",{count:"exact",head:true}).eq("status","new"),sb.from("admission_applications").select("*",{count:"exact",head:true}).eq("status","review")]);$("#sNews").textContent=q[0].count||0;$("#sAnn").textContent=q[1].count||0;$("#sNew").textContent=q[2].count||0;$("#sReview").textContent=q[3].count||0}
async function loadNews(){const {data}=await sb.from("news_articles").select("*").order("created_at",{ascending:false});news=data||[];$("#newsRows").innerHTML=news.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.category||"")}</td><td><span class="status">${esc(x.status)}</span></td><td><button class="btn secondary" data-n="${x.id}">Edit</button></td></tr>`).join("")||`<tr><td colspan="4">No news yet.</td></tr>`;$$("[data-n]").forEach(b=>b.onclick=()=>openNews(b.dataset.n))}
function openNews(id){const f=$("#newsForm");f.reset();f.elements.id.value="";if(id){const x=news.find(y=>y.id===id);f.elements.id.value=x.id;f.elements.title.value=x.title;f.elements.category.value=x.category||"School";f.elements.status.value=x.status;f.elements.excerpt.value=x.excerpt||"";f.elements.content.value=x.content||""}$("#newsModal").classList.add("open")}
$("#newNews").onclick=()=>openNews()
$("#newsForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=new FormData(f),id=d.get("id");let image_url=id?news.find(x=>x.id===id)?.image_url:null,img=d.get("image");if(img?.size){const p=`news/${crypto.randomUUID()}.${img.name.split(".").pop()||"jpg"}`;const {error}=await sb.storage.from("website-media").upload(p,img);if(error){alert(error.message);return}image_url=sb.storage.from("website-media").getPublicUrl(p).data.publicUrl}const payload={title:d.get("title"),slug:d.get("title").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),category:d.get("category"),status:d.get("status"),excerpt:d.get("excerpt"),content:d.get("content"),image_url,created_by:user.id,updated_at:new Date().toISOString(),published_at:d.get("status")==="published"?new Date().toISOString():null};const {error}=id?await sb.from("news_articles").update(payload).eq("id",id):await sb.from("news_articles").insert(payload);if(error){alert(error.message);return}$("#newsModal").classList.remove("open");loadNews();stats()}
async function loadAnns(){const {data}=await sb.from("announcements").select("*").order("priority",{ascending:false});anns=data||[];$("#annRows").innerHTML=anns.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.message)}</td><td>${x.priority}</td><td><span class="status">${x.is_active?"active":"inactive"}</span></td><td><button class="btn secondary" data-a="${x.id}">Edit</button></td></tr>`).join("")||`<tr><td colspan="5">No announcements yet.</td></tr>`;$$("[data-a]").forEach(b=>b.onclick=()=>openAnn(b.dataset.a))}
function openAnn(id){const f=$("#annForm");f.reset();f.elements.id.value="";if(id){const x=anns.find(y=>y.id===id);f.elements.id.value=x.id;f.elements.title.value=x.title;f.elements.message.value=x.message;f.elements.link_url.value=x.link_url||"";f.elements.priority.value=x.priority;f.elements.is_active.value=String(x.is_active)}$("#annModal").classList.add("open")}
$("#newAnn").onclick=()=>openAnn()
$("#annForm").onsubmit=async e=>{e.preventDefault();const d=new FormData(e.currentTarget),id=d.get("id"),p={title:d.get("title"),message:d.get("message"),link_url:d.get("link_url")||null,priority:Number(d.get("priority")||10),is_active:d.get("is_active")==="true",created_by:user.id,updated_at:new Date().toISOString()};const {error}=id?await sb.from("announcements").update(p).eq("id",id):await sb.from("announcements").insert(p);if(error){alert(error.message);return}$("#annModal").classList.remove("open");loadAnns();stats()}
async function loadAdms(){const {data}=await sb.from("admission_applications").select("*").order("created_at",{ascending:false});adms=data||[];render();$("#recent").innerHTML=adms.slice(0,5).map(x=>`<p><strong>${esc(x.reference_number)}</strong> — ${esc(x.student_first_name+" "+x.student_last_name)} — ${esc(x.status)}</p>`).join("")||"No applications yet."}
function render(){const f=$("#filter").value,rows=adms.filter(x=>f==="all"||x.status===f);$("#admRows").innerHTML=rows.map(x=>`<tr><td>${esc(x.reference_number)}</td><td>${esc(x.student_first_name+" "+x.student_last_name)}</td><td>${esc(x.applying_for_class)}</td><td>${esc(x.parent_name)}</td><td><span class="status">${esc(x.status)}</span></td><td><button class="btn secondary" data-v="${x.id}">View</button></td></tr>`).join("")||`<tr><td colspan="6">No applications.</td></tr>`;$$("[data-v]").forEach(b=>b.onclick=()=>viewAdm(b.dataset.v))}
$("#filter").onchange=render
function viewAdm(id){const x=adms.find(y=>y.id===id);$("#admDetail").innerHTML=`<div class="grid2"><div class="card"><h3>Student</h3><p><strong>${esc(x.student_first_name+" "+x.student_last_name)}</strong></p><p>Class: ${esc(x.applying_for_class)}</p><p>Current school: ${esc(x.current_school||"—")}</p></div><div class="card"><h3>Parent</h3><p><strong>${esc(x.parent_name)}</strong></p><p>${esc(x.parent_phone)}</p><p>${esc(x.parent_email)}</p></div></div><div class="field"><label>Status</label><select id="admStatus">${["new","review","contacted","assessment","offered","accepted","declined","closed"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Internal Note</label><textarea id="admNote">${esc(x.internal_note||"")}</textarea></div><button class="btn primary" id="saveAdm">Save Changes</button>`;$("#admModal").classList.add("open");$("#saveAdm").onclick=async()=>{await sb.from("admission_applications").update({status:$("#admStatus").value,internal_note:$("#admNote").value,reviewed_by:user.id,updated_at:new Date().toISOString()}).eq("id",id);$("#admModal").classList.remove("open");loadAdms();stats()}}
boot()
